Add packaging with poetry
distributed-system-analysis/smallfile pull request #40
Opened 2022-11-07 16:18 UTC by sandrobonazzola

Add packaging using poetry

Help installing the package as `pip install https://github.com/distributed-system-analysis/smallfile.git@main`
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

2022-11-07 16:46 UTC, portante requested changes
Let's also drop `setup.cfg` and `requirements.txt` (making sure they are both properly covered by `pyproject.toml`), and then update the `README.md` where necessary to describe the use of `poetry`.

2022-11-08 08:38 UTC, sandrobonazzola commented
> Let's also drop `setup.cfg` and `requirements.txt` (making sure they are both properly covered by `pyproject.toml`), and then update the `README.md` where necessary to describe the use of `poetry`.

Ok for dropping `requirements.txt` but we can't remove `setup.cfg`because pycodestyle and flake8 doesn't accept configuration via `pyproject.toml` yet.

2022-11-08 12:09 UTC, portante requested changes

2022-11-08 12:09 UTC, portante commented on setup.cfg
> +# pycodestyle doesn't support pyproject.toml yet
Where is `pycodestyle` invoked?  I only see the configuration here.  The pre-commit hook has `black` in it and `isort`.  We should probably add a GitHub action to run `black` and `isort` checks, and add a flake8 check to both as well.

2022-11-08 12:09 UTC, portante commented on setup.cfg
> +# flake8 doesn't support pyproject.toml yet
I believe `flake8` can use a `.flake8` file instead so that we can make it specific to `flake8`.

2022-11-09 08:34 UTC, sandrobonazzola commented on setup.cfg
> +# pycodestyle doesn't support pyproject.toml yet
`pycodestyle` is taken in by `flake8` run. I think we can override the pycodestyle config with the flake8 one.

2022-11-09 08:43 UTC, sandrobonazzola commented on setup.cfg
> +# pycodestyle doesn't support pyproject.toml yet
The GitHub action already exists: https://github.com/distributed-system-analysis/smallfile/blob/main/.github/workflows/code_check.yaml

2022-11-10 03:35 UTC, portante approved these changes

2022-11-10 03:35 UTC, merged