windows: Fix open fd error on windows
distributed-system-analysis/smallfile pull request #41
Opened 2023-05-08 22:06 UTC by rafikc30

Unlike linux, windows will not allow a rename to
happen if there is an open fd. Hence, closing the
fd's before renaming

2023-05-09 17:03 UTC, portante requested changes

2023-05-09 17:03 UTC, portante commented on sync_files.py
>          os.rename(fpath + notyet, fpath)
I suspect that you can just move the `os.rename()` out from under the `with` statement:

```
with open(fpath + notyet, "w") as sgf:
    sgf.write(contents)
    sgf.flush()
    os.fsync(sgf.fileno())  # file should close when you exit block
os.rename(fpath + notyet, fpath)
```

2023-05-09 18:57 UTC, rafikc30 commented on sync_files.py
>          os.rename(fpath + notyet, fpath)
@portante  Thanks for the suggestions. I will resend it

2023-05-16 21:57 UTC, rafikc30 commented on sync_files.py
>          os.rename(fpath + notyet, fpath)
@portante done

2023-05-17 11:20 UTC, portante commented
FWIW, I fixed in the failing `black` check in PR #42.

2023-05-17 11:20 UTC, merged